global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 10s

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
 - "alerting_rules.yml"
# - /etc/prometheus/alerting_rules.yml

#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "trickyplayapi"
    scheme: "https"
    tls_config:
      insecure_skip_verify: true
    metrics_path: "/actuator/prometheus"
    scrape_interval: 60s
    static_configs:
      - targets: ["trickyplay-api:9090"]
        labels:
          application: "trickyplay-api-actuator"
    bearer_token_file: "/run/secrets/prom_bearer"
#    bearer_token: "token_here"
#    basic_auth:
#      username: "user"
#      password: "password"