spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
application:
  security:
    jwt:
      secret-key: ${TEST_JWT_SECRET_KEY}
      refresh-token-expiration: ${TEST_REFRESH_TOKEN_EXPIRATION} # [ms]
      access-token-expiration: ${TEST_ACCESS_TOKEN_EXPIRATION} # [ms]