spring:
  datasource:
    url: jdbc:mysql://${TEST_MYSQL_HOST}:${TEST_MYSQL_PORT}/${TEST_MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${TEST_MYSQL_USERNAME}
    password: ${TEST_MYSQL_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${PROD_APPLICATION_PORT}
  error:
    include-stacktrace: never
application:
  security:
    jwt:
      secret-key: ${TEST_JWT_SECRET_KEY}
      refresh-token-expiration: ${TEST_REFRESH_TOKEN_EXPIRATION} # [ms]
      access-token-expiration: ${TEST_ACCESS_TOKEN_EXPIRATION} # [ms]