spring:
  datasource:
    url: jdbc:mysql://${PROD_MYSQL_HOST}:${PROD_MYSQL_PORT}/${PROD_MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
server:
  port: ${PROD_APPLICATION_PORT}
  error:
    include-stacktrace: never
application:
  security:
    jwt:
      secret-key: ${PROD_JWT_SECRET_KEY}
      refresh-token-expiration: ${PROD_REFRESH_TOKEN_EXPIRATION} # [ms]
      access-token-expiration: ${PROD_ACCESS_TOKEN_EXPIRATION} # [ms]